version: '3.8'

services:
  bibliotech-frontend:
    build: .
    container_name: bibliotech-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"